const fs = require("fs");
const {
  Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType,
  Table, TableRow, TableCell, WidthType, ShadingType,
} = require("docx");

const H1 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 340, after: 170 }, children: [new TextRun({ text: t, bold: true })] });
const H2 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 120 }, children: [new TextRun({ text: t, bold: true })] });
const P = (t, opts = {}) => new Paragraph({ spacing: { after: 150, line: 312 }, alignment: AlignmentType.JUSTIFIED, ...opts, children: [new TextRun(t)] });
const PI_ = (t) => new Paragraph({ spacing: { after: 150, line: 312 }, children: [new TextRun({ text: t, italics: true })] });

const cell = (t, bold = false, shade = false, w = 2340) => new TableCell({
  width: { size: w, type: WidthType.DXA },
  shading: shade ? { type: ShadingType.CLEAR, fill: "EDF1F7" } : undefined,
  margins: { top: 60, bottom: 60, left: 100, right: 100 },
  children: [new Paragraph({ children: [new TextRun({ text: t, bold, size: 19 })] })],
});
const row3 = (a, b, c, hdr = false) => new TableRow({ children: [cell(a, hdr, hdr, 3744), cell(b, hdr, hdr, 2808), cell(c, hdr, hdr, 2808)] });
const row4 = (a, b, c, d, hdr = false) => new TableRow({ children: [cell(a, hdr, hdr), cell(b, hdr, hdr), cell(c, hdr, hdr), cell(d, hdr, hdr)] });
const rowM = (a, b, c, hdr = false) => new TableRow({ children: [cell(a, hdr, hdr, 3100), cell(b, hdr, hdr, 2000), cell(c, hdr, hdr, 4260)] });

const t1 = new Table({ width: { size: 9360, type: WidthType.DXA }, columnWidths: [3744, 2808, 2808], rows: [
  row3("Characteristic", "SSI (n=20)", "No SSI (n=190)", true),
  row3("Photographs, n", "188", "1,760"),
  row3("Photographs per patient, median (IQR)", "6 (3–13)", "8 (5–11)"),
  row3("Imaged by POD 7, n (%)", "20 (100%)", "178 (94%)"),
  row3("Incision length, cm, mean±SD (n recorded)", "22.7±8.3 (12)", "17.5±4.2 (114)"),
]});
const t2 = new Table({ width: { size: 9360, type: WidthType.DXA }, columnWidths: [2340, 2340, 2340, 2340], rows: [
  row4("Architecture", "Patient AUROC, mean±SD (3 seeds)", "Range", "Paired Δ vs ResNet18 (P)", true),
  row4("EfficientNet-B0", "0.755±0.037", "0.727–0.797", "-0.048 to +0.021 (0.46–0.78)"),
  row4("ResNet18", "0.731±0.052", "0.674–0.776", "Reference; within-architecture Δ -0.102 (0.09)"),
  row4("ViT-B/16", "0.725±0.049", "0.677–0.774", "-0.002 to -0.099 (0.10–0.93)"),
]});
const t3 = new Table({ width: { size: 9360, type: WidthType.DXA }, columnWidths: [3100, 2000, 4260], rows: [
  rowM("Input condition", "Patient AUROC", "Paired contrast (P)", true),
  rowM("Full image", "0.725", "Reference"),
  rowM("Wound-only (true mask)", "0.670", "vs full -0.055 (0.62)"),
  rowM("Background-only (true mask)", "0.821", "vs full +0.097 (0.09)"),
  rowM("Sham wound (relocated mask)", "0.817", "vs true background -0.005 (0.94); vs true wound +0.147 (0.08)"),
  rowM("Sham background", "0.654", "vs full -0.071 (0.16)"),
]});

const doc = new Document({
  styles: { default: { document: { run: { font: "Calibri", size: 21 } } } },
  sections: [{
    properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } } },
    children: [
      H1("Methods"),
      H2("Study design and setting"),
      P("We conducted a prospective feasibility study of smartphone-based surveillance for surgical site infection (SSI) at a single academic center. Patients submitted serial photographs of their surgical incision during the 30-day postoperative period. The study was designed around a practical question: how much infection-related information is actually present in a single smartphone photograph? The goal was not to build the highest-performing classifier possible, but to test whether the image itself contains enough signal to support prospective surveillance. Reporting follows TRIPOD guidance for prediction models and STROBE where applicable. The analysis plan was specified before exposure-outcome modeling."),
      H2("Participants and cohort"),
      P("Adults undergoing surgery with a qualifying incision were participants. After quality gating, the analytic dataset contained 1,948 photographs from 210 patients, of whom 20 (9.5%) developed an SSI within 30 days. Before the cohort was locked, enrollment and outcome records were adjudicated. One duplicate enrollment was resolved by retaining the SSI-positive record, consent withdrawals were identified and excluded, and SSI labels and diagnosis dates were reviewed. These adjudication steps did not change the final analytic cohort of 210 patients with 20 SSI events."),
      H2("Image acquisition and quality gating"),
      P("Photographs were captured by patients or clinical staff using their own smartphones. A protocolized quality and dressing gate was applied without knowledge of SSI outcome. Images passed when the incision was visible and not covered by a dressing; dressing-covered, non-wound, or otherwise unusable images were excluded. Gate passage was 56% among photographs from SSI-positive patients and 60% among photographs from SSI-negative patients. This gate was treated as a reproducible pipeline step rather than manual selection of images that looked diagnostically useful."),
      P("All analyses used one locked master image-to-fold map containing 1,948 unique photographs. Patients, rather than images, were assigned to folds so that photographs from the same patient could not appear in both training and validation data. The fold map was fixed under seed 42 and reused across the analyses."),
      H2("Reference standard"),
      P("The outcome was 30-day SSI based on CDC/NHSN criteria from structured chart review. Study photographs were not available to the adjudicating team and did not contribute to the clinical diagnosis. This kept the index images independent from the reference standard."),
      H2("Primary estimand and outcome"),
      P("The primary analysis used a postoperative day (POD) 7 landmark. It asked whether images available by POD 7 could predict an SSI that had not yet been diagnosed. Patients already diagnosed by POD 7 were therefore excluded from the primary risk set. Two SSI-positive patients with diagnosis dates that could not be adjudicated were also excluded where timing was required. The final POD-7 risk set included 193 patients, 15 of whom later developed SSI."),
      P("For each patient, the primary score was the mean model probability across all photographs available through POD 7. Photographs without an explicit day label were assigned to the day-of-surgery baseline by convention. Two prespecified sensitivity analyses used the latest photograph available through POD 7 and the photograph closest to POD 7. This setup was chosen to make the main analysis prospective: the model only had access to information that would have been available before the diagnosis it was trying to predict."),
      H2("Model development and validation"),
      P("We evaluated ResNet18, EfficientNet-B0, and ViT-B/16. Each model was initialized with ImageNet-pretrained weights and fine-tuned end to end. Images were resized to 224 × 224 pixels. Training used class-weighted cross-entropy, AdamW optimization, horizontal and vertical flip augmentation, and 12 epochs. The learning rate was 1×10^-4 for the convolutional models and 3×10^-5 for ViT-B/16."),
      P("Validation used patient-grouped five-fold cross-validation with strictly out-of-fold predictions. Patient-level scores were calculated by averaging that patient's image probabilities. Each architecture was trained using three random seeds on the same locked folds. All reported performance estimates and resampling procedures were clustered at the patient level so that multiple images from one patient were not treated as independent observations."),
      H2("Statistical analysis"),
      P("AUROC and AUPRC were the main discrimination metrics. AUPRC was reported alongside AUROC because SSI prevalence was low and a ranking metric alone can make performance look more useful than it is in practice. Brier score and calibration slope/intercept were used to describe probability quality. Confidence intervals were generated with 2,000 patient-level clustered bootstrap resamples. Model comparisons were paired within the same bootstrap replicate."),
      P("The POD-7 analysis and its leak-sensitivity analysis formed the prespecified confirmatory set. The remaining analyses were treated as exploratory and interpreted mainly through effect sizes, confidence intervals, and behavior across seeds rather than isolated P values. Given the small number of SSI events, model differences were also considered against the observed resolution of the design; paired AUROC intervals commonly had half-widths of roughly 0.10 to 0.16."),
      H2("Information audit and confounding analyses"),
      P("We used four complementary probes to understand where model performance was coming from."),
      P("First, we compared architecture and seed effects using the same patient folds. This allowed us to see whether changing model family produced a consistent benefit compared with ordinary training variability."),
      P("Second, we trained context-only models that did not use wound pixels. These models used postoperative day, image-acquisition characteristics, prior imaging behavior, or a combination of these variables. Prior-behavior features were constructed using only information available before the image being scored. The purpose was to test whether when and how a photograph was obtained could itself carry outcome-related information."),
      P("Third, we performed spatial masking experiments. Models were retrained using the full image, wound-only input, background-only input, and randomly relocated equal-area sham masks. Expert incision annotations included incision-line strips and wound-bed polygons with a tolerance band. The sham conditions were important because masking changes image geometry and available pixel area even when the mask has no biological relationship to the wound."),
      P("Fourth, we used normal postoperative healing stage as a positive-control task. The same images and modeling pipeline were used to predict healing stage. This tested whether the pipeline was capable of learning a strong visual signal from the dataset when such a signal was present."),
      H2("Calibration, operating points, and decision curves"),
      P("Raw out-of-fold scores were used for discrimination analyses. Cross-fold Platt scaling was used for probability calibration and operating-point analyses. Recalibration was unstable at this event count, and isotonic calibration was degenerate, so these results were interpreted cautiously. Prespecified operating points included a fixed-specificity point and a high-sensitivity rule-out point. We report sensitivity, specificity, and the fraction of patients flagged. Decision-curve net benefit was compared with treat-all and treat-none strategies over a clinically plausible threshold range."),
      H2("Comparative analyses"),
      P("Image, clinical, and combined models were compared on the locked cohort using paired changes in AUROC and AUPRC. The clinical comparator used intraoperative covariates only. Chart-review-derived variables were not used in the primary clinical specification because the availability of chart-review data was itself associated with SSI status. Numeric intraoperative covariates were range-checked for physiologic plausibility in the final specification (temperature values outside 30–43 °C, 11 entries, were set to missing); results from the earlier unrepaired specification were kept only as a sensitivity analysis rather than treated as the main clinical comparison."),
      P("A separate exploratory analysis compared model predictions with clinician ratings on the same image set. Fifteen clinicians rated the shared images. Inter-rater agreement was measured with Fleiss kappa, and surgeons were compared with non-surgeons. The main model-versus-clinician contrast was restricted to pre-diagnosis images because only a few SSI-positive patients were represented in the shared rated subset."),
      H2("Reproducibility"),
      P("The analysis pipeline was run using a fixed seed set and a locked master fold map. Row-level out-of-fold predictions were retained for each architecture, seed, and masking condition. The masking cohort audit records exclusions and annotation availability, and analysis code is organized by stage so that the main results can be reproduced from the locked inputs."),

      H1("RESULTS"),
      H2("Cohort and image characteristics"),
      P("The cohort included 1,948 quality-gated photographs from 210 adults. Twenty patients (9.5%) developed an SSI within 30 days. Patients submitted a median of 8 photographs overall, with a median of 6 among patients who developed SSI and 8 among patients who did not. The overall interquartile range was 5–11 photographs, with a range of 1–43. Imaging included day-of-surgery baseline photographs and protocol follow-up during the postoperative period, with additional off-schedule photographs submitted by some patients. By POD 7, 94% of patients had submitted at least one photograph. Because the cohort contained only 20 SSI events, all interval estimates in this study are wide, and null findings should not be read as evidence of equivalence."),
      PI_("Table 1. Cohort and imaging characteristics by SSI status."),
      t1,
      P("The different analyses used nested subsets of this 210-patient cohort. The leak-sensitivity analysis included 204 patients after excluding two SSI-positive patients without adjudicable diagnosis dates and four patients without dated photographs. The POD-7 risk set then excluded patients who had already been diagnosed by day 7, leaving 193 patients and 15 subsequent infections. The masking analysis was based on annotation availability and included 206 patients with 19 SSI events and 1,886 photographs.", { spacing: { before: 150, after: 150, line: 312 } }),
      H2("Primary pre-diagnosis discrimination"),
      P("In the POD-7 risk set, the image-only model achieved an AUROC of 0.761 (95% CI 0.645–0.860) and an AUPRC of 0.172. SSI prevalence in this risk set was 7.8%. Using the latest available photograph through POD 7 produced an AUROC of 0.746, while using the photograph closest to POD 7 produced an AUROC of 0.744. The similar results across these aggregation choices suggest that the main estimate was not being driven by one specific way of combining a patient's photographs."),
      H2("Estimand robustness"),
      P("Restricting positive patients to photographs obtained strictly before diagnosis had little effect on the pooled patient-level estimate. The paired same-patient change was +0.007 (95% CI -0.011 to +0.025; P=0.44) among 204 patients, including 18 SSI events with adjudicated diagnosis dates. A descriptive all-images analysis gave a patient-level AUROC of 0.779. This suggests that the observed discrimination was not simply caused by including photographs taken after the infection had already been diagnosed. In addition, 318 photographs lacked an explicit day label and were assigned to the day-of-surgery baseline by convention; a sensitivity analysis excluding these photographs gave a POD-7 AUROC of 0.730 (187 patients, 14 events)."),
      H2("Architecture and seed variability"),
      P("Across three seeds, mean patient-level AUROC was 0.755±0.037 for EfficientNet-B0, 0.731±0.052 for ResNet18, and 0.725±0.049 for ViT-B/16. No architecture significantly outperformed another, with paired P values ranging from 0.10 to 0.93. Rankings also changed across seeds. The largest within-architecture contrast was observed between two ResNet18 seeds (-0.102; P=0.09), which was only slightly larger than the biggest between-architecture contrast (-0.099; P=0.10). In other words, ordinary seed-to-seed variation was on about the same scale as the architecture differences we observed."),
      PI_("Table 2. Fold-paired architectures on the locked master map. All models used identical folds and training procedures across three seeds."),
      t2,
      P("Training-size experiments gave mean AUROCs of 0.718±0.016 with one-third of the training patients, 0.746±0.057 with two-thirds, and 0.755±0.037 with the full training cohort. There was no clear monotonic increase, although the study was too small to rule out a true architecture or data-size effect below the resolution we could detect.", { spacing: { before: 150, after: 150, line: 312 } }),
      H2("Confound and context probes"),
      P("Postoperative day alone performed near chance at the image level. At the patient level, the image model performed better than each single context probe across seeds: the mean difference was +0.067±0.052 versus postoperative day, +0.058±0.052 versus acquisition characteristics, and +0.061±0.052 versus prior imaging behavior. However, a combined context-only model using acquisition characteristics, imaging behavior, and postoperative day approximately matched the image model, with a mean difference of -0.009±0.052."),
      H2("Spatial localization: masking with sham controls"),
      P("The masking analysis included 1,886 photographs from 206 patients, including 19 patients with SSI. One SSI-positive patient did not have an available annotation source and was excluded from this analysis. Patient-level AUROC was 0.725 for the full image, 0.670 for wound-only input, and 0.821 for background-only input. The wound-only model did not outperform the full-image model."),
      P("The sham controls changed how these masking results should be interpreted. A randomly relocated equal-area mask produced an AUROC of 0.817, almost the same as the true background condition (difference -0.005; P=0.94). The true wound crop was numerically worse than the equal-area random patch, with a difference of +0.147 in favor of the sham condition (P=0.08). The apparent background-versus-full advantage also did not persist against its own sham control (P=0.16). Similar effects could therefore be produced by mask geometry alone, without the mask being placed over the actual wound."),
      PI_("Table 3. Masked retraining with sham controls (annotation-available frame; frozen master folds; paired patient-bootstrap contrasts)."),
      t3,
      H2("Healing-stage positive control"),
      P("Using the same photographs and essentially the same pipeline, normal postoperative healing stage was identified with an AUROC of about 0.975. This was much higher than the roughly 0.755 AUROC observed for SSI in the comparable architecture analyses.", { spacing: { before: 150, after: 150, line: 312 } }),
      H2("Calibration and operating points"),
      P("For the POD-7 primary analysis, Platt-scaled probabilities gave a Brier score of 0.075 (95% CI 0.047–0.106) and a calibration slope of 0.63 (95% CI 0.30–1.05). At 80% specificity, sensitivity was 0.67 and 24% of patients were flagged. A higher-sensitivity threshold detected 14 of 15 infections (93%) but flagged 51% of patients, corresponding to a specificity of 0.53. Predictive values are not emphasized because the analysis contained only 20 total SSI events."),
      H2("Image versus clinical versus combined models"),
      P("In the final range-checked specification on the locked cohort, AUROC was 0.747 for the clinical model, 0.779 for the image model, and 0.794 for the combined model. The combined-versus-clinical difference was not significant (ΔAUROC +0.048; P=0.13). This clinical model used intraoperative values only, whose availability was unrelated to outcome (coverage-indicator AUROC 0.49); its numerical similarity to the excluded chart-review coverage indicator (0.75) is coincidental — the excluded indicator is a bare availability flag reflecting outcome-enriched chart-review selection, whereas 0.747 reflects discrimination from variables recorded at surgery."),
      P("Before range-checking, the same comparison produced a larger apparent difference (Δ +0.116; P=0.013 at the primary cross-validation partition). That result was not stable: the corresponding P values were 0.17 and 0.20 in two alternative partitions, and the difference also disappeared when the image component was limited to pre-diagnosis photographs (Δ +0.025; P=0.67). The apparent gain was therefore not robust to range-checking, partition choice, or restriction to information available before diagnosis."),
      P("Within the leak-free POD-7 risk set, the combined model did not improve AUROC over the image model (Δ -0.020; P=0.80). AUPRC was 0.277 for the combined model and 0.172 for the image model, but this difference was also not significant (Δ +0.106; P=0.18), and the decision curves overlapped. A clinical model based on chart-reviewed variables was excluded because simply knowing whether those variables were available predicted SSI with an AUROC of about 0.75."),
      H2("Model versus clinicians"),
      P("Fifteen clinicians rated a shared image set. Inter-rater agreement was slight (Fleiss κ=0.105), and there was no meaningful difference between surgeons and non-surgeons. On the shared set restricted to pre-diagnosis images, AUROC was 0.89 for the model and 0.63 for the clinician consensus. Only three SSI-positive patients were represented in this subset, and the difference was not statistically significant (P=0.33). We therefore treat this comparison as exploratory."),

      H1("DISCUSSION"),
      P("In this cohort, smartphone photographs obtained before diagnosis contained a moderate amount of information about subsequent SSI risk. At the POD-7 landmark, the image-only model achieved an AUROC of 0.761 and an AUPRC of 0.172. Performance did not consistently improve when moving among ResNet18, EfficientNet-B0, and ViT-B/16, and the relative ranking of the architectures varied across random seeds. At the same time, a context-only model based on acquisition characteristics, imaging behavior, and postoperative day performed nearly as well as the image model. The masking experiments also provided little evidence that the models were relying specifically on the wound region, since randomly placed sham masks produced effects similar to those of the true masks. Together, these findings suggest that the photographs do contain predictive information, but that the circumstances in which the images are collected may contribute nearly as much signal as the wound appearance itself. For remote surveillance, the process by which an image is generated and submitted therefore appears to be part of the prediction problem."),
      P("An AUROC of approximately 0.76 should also be distinguished from the question of whether the model would be useful as a screening tool. AUROC measures ranking ability, but it does not show how many clinically useful alerts a system would generate when the outcome is uncommon. The AUPRC was 0.172 in a POD-7 cohort with an SSI prevalence of 7.8% (a precision floor of 0.078), meaning precision was only about twice the prevalence baseline. This is better than chance, but still limited for image-only screening. The operating characteristics make the tradeoff more concrete: identifying 14 of 15 subsequent infections required flagging 51% of patients. In other words, a model can separate higher- and lower-risk patients reasonably well while still producing too many alerts to work effectively on its own."),
      P("The healing-stage positive control provides some of the clearest evidence that this limitation is related, at least in part, to the information contained in the images rather than simply to the modeling approach. Using the same photographs and a nearly identical pipeline, normal postoperative stage could be predicted with an AUROC of approximately 0.975, whereas SSI prediction remained near 0.755 in comparable analyses. This suggests that the pipeline can extract a strong signal when one is clearly visible in the photographs. The architecture and training-size analyses point in the same direction, although they should be interpreted more cautiously. With only 15 to 20 events and relatively wide paired intervals, the study may not have had enough power to detect a meaningful difference between architectures. We therefore view these results as evidence consistent with an input limitation, rather than proof that model capacity is irrelevant."),
      P("Several factors could explain why the image signal depends so heavily on context. Dressings, framing, surrounding skin, body site, postoperative timing, and even the decision to submit an additional photograph may all vary according to how a patient is recovering. The masking experiment is especially informative in this respect. A randomly relocated mask covering the same area produced effects similar to those seen with the true wound mask. This means that masking or ablation alone cannot establish that a model is using wound-specific biological information. If altering image geometry is enough to produce the same result, then a heatmap or incision crop should not automatically be interpreted as evidence of biological localization. This is relevant to prior SSI-imaging studies that have used CAMs, attention maps, or incision ablation to argue that a model is focusing on clinically meaningful regions."),
      P("Skin tone is another important consideration. Erythema is a major visual feature used by clinicians when assessing infection, yet photography may capture this feature less reliably in darker skin. If the information available from a single photograph is already limited, those limitations may not affect all patients equally. This deserves direct evaluation in future cohorts rather than being inferred from aggregate performance."),
      P("The comparison with clinical models also depends on using the correct prospective frame. In the full cohort, an earlier version of the combined model appeared to outperform the clinical model significantly. That result, however, was not robust to physiologic range checking, alternative cross-validation partitions, or restriction of the image component to photographs obtained before diagnosis. In the final range-checked analysis, the difference between the combined and clinical models was smaller and no longer statistically significant. More importantly, in the leak-free POD-7 risk set, adding clinical information did not improve AUROC over the image-only model, and the increase in AUPRC remained uncertain."),
      P("This distinction matters because the full cohort may contain information that becomes available only after infection has already started to declare itself. The POD-7 analysis instead asks a more difficult and clinically relevant question: what can be predicted before diagnosis? Our conclusion that single photographs contain limited unique information therefore applies specifically to prospective surveillance, rather than to every possible diagnostic use of postoperative wound images."),
      P("The main contribution of this study is therefore less the observation that wound photographs are imperfect and more the attempt to audit what information the models are actually using. Image-based AI performs extremely well when diagnostically relevant information is strongly encoded in the pixels, as seen in areas such as diabetic retinopathy, skin cancer, and histopathology. The same general transfer-learning approach produced substantially weaker results here. That contrast suggests that the observed performance plateau is unlikely to be explained simply by failure to select a more advanced architecture."),
      P("Previous smartphone-based SSI studies have likewise reported moderate image performance or improvements from incorporating non-image information, but localization is often supported primarily through CAMs or visual inspection of attention maps. To our knowledge, prior work has not combined a prospective pre-diagnosis estimand with sham-controlled localization, architecture-by-seed comparisons, context-only probes, and a positive-control task using the same images. Taken together, these analyses allow the study to ask not only whether a classifier performs well, but also what kind of information the dataset is making available to it."),
      P("The study has several strengths. Images were collected prospectively, patients rather than individual photographs were grouped across folds, predictions were generated strictly out of fold, and the primary estimand was aligned with information available before diagnosis. The images were also independent of the reference standard. Rather than relying on a single model result, we examined the same underlying signal through several complementary analyses."),
      P("The main limitation is statistical precision. The primary estimate is based on only 15 subsequent infections, and its 95% confidence interval of 0.645 to 0.860 spans performance ranging from modest to potentially clinically meaningful. The point estimate should therefore be viewed as the best estimate from this cohort rather than a precise measurement. Other limitations include the single-center design, an uncontrolled smartphone acquisition workflow, missing scheduled photographs and postoperative-day labels, annotation-based exclusions in the masking subset, variability across models and seeds, the exploratory nature of the clinician comparison, and the absence of external validation. We also did not evaluate performance by skin tone, which is particularly important given the role of erythema in visual SSI assessment."),
      P("Overall, these findings support using smartphone photographs as one component of a broader prospective surveillance system rather than as a standalone diagnostic screen. More standardized image acquisition, calibrated decision support with clearly defined alert or rule-out rates, and external validation in independent cohorts would help clarify their clinical value. Future datasets should also include sufficient diversity in skin tone to allow performance differences to be measured directly."),
      P("From a methodological perspective, our findings also suggest that wound-image AI studies should include sham or permutation-based spatial controls and report performance across multiple seeds rather than relying on a single attention map or training run. Taken together, the results are consistent with an information limit in single RGB wound photographs. The images are informative, but they appear to be incomplete diagnostic inputs on their own, and at least part of that limitation seems to reflect what the photograph captures rather than only how the model is built."),
    ],
  }],
});

Packer.toBuffer(doc).then((buf) => {
  fs.writeFileSync(process.argv[2] || "PAPER1_zain_revision_fixed.docx", buf);
  console.log("DOCX_WRITTEN");
});
