const fs = require("fs");
const {
  Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType,
  Table, TableRow, TableCell, WidthType, ShadingType, PageBreak,
} = require("docx");

const H1 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 340, after: 170 }, children: [new TextRun({ text: t, bold: true })] });
const H2 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 120 }, children: [new TextRun({ text: t, bold: true })] });
const P = (runs, opts = {}) => new Paragraph({ spacing: { after: 150, line: 312 }, alignment: AlignmentType.JUSTIFIED, ...opts, children: Array.isArray(runs) ? runs : [new TextRun(runs)] });
const T = (t) => new TextRun({ text: t });
const I = (t) => new TextRun({ text: t, italics: true });
const FLAG = (t) => new TextRun({ text: t, italics: true, highlight: "yellow" });

const cell = (t, bold = false, shade = false, w = 2340) => new TableCell({
  width: { size: w, type: WidthType.DXA },
  shading: shade ? { type: ShadingType.CLEAR, fill: "EDF1F7" } : undefined,
  margins: { top: 60, bottom: 60, left: 100, right: 100 },
  children: [new Paragraph({ children: [new TextRun({ text: t, bold, size: 19 })] })],
});

const t1 = new Table({ width: { size: 9360, type: WidthType.DXA }, columnWidths: [3744, 2808, 2808], rows: [
  new TableRow({ children: [cell("Characteristic", true, true, 3744), cell("SSI (n=20)", true, true, 2808), cell("No SSI (n=190)", true, true, 2808)] }),
  new TableRow({ children: [cell("Photographs, n", false, false, 3744), cell("188", false, false, 2808), cell("1,760", false, false, 2808)] }),
  new TableRow({ children: [cell("Photographs per patient, median (IQR)", false, false, 3744), cell("6 (3–13)", false, false, 2808), cell("8 (5–11)", false, false, 2808)] }),
  new TableRow({ children: [cell("Imaged by POD 7, n (%)", false, false, 3744), cell("20 (100%)", false, false, 2808), cell("178 (94%)", false, false, 2808)] }),
  new TableRow({ children: [cell("Incision length, cm, mean±SD (n recorded)", false, false, 3744), cell("22.7±8.3 (12)", false, false, 2808), cell("17.5±4.2 (114)", false, false, 2808)] }),
]});

const t2 = new Table({ width: { size: 9360, type: WidthType.DXA }, columnWidths: [2340, 2340, 2340, 2340], rows: [
  new TableRow({ children: [cell("Architecture", true, true), cell("Patient AUROC, mean±SD (3 seeds)", true, true), cell("Range", true, true), cell("Paired Δ vs ResNet18 (P)", true, true)] }),
  new TableRow({ children: [cell("EfficientNet-B0"), cell("0.755±0.037"), cell("0.727–0.797"), cell("−0.048 to +0.021 (0.46–0.78)")] }),
  new TableRow({ children: [cell("ResNet18"), cell("0.731±0.052"), cell("0.674–0.776"), cell("Reference; within-architecture Δ −0.102 (0.09)")] }),
  new TableRow({ children: [cell("ViT-B/16"), cell("0.725±0.049"), cell("0.677–0.774"), cell("−0.002 to −0.099 (0.10–0.93)")] }),
]});

const t3 = new Table({ width: { size: 9360, type: WidthType.DXA }, columnWidths: [3100, 2000, 4260], rows: [
  new TableRow({ children: [cell("Input condition", true, true, 3100), cell("Patient AUROC", true, true, 2000), cell("Paired contrast (P)", true, true, 4260)] }),
  new TableRow({ children: [cell("Full image", false, false, 3100), cell("0.725", false, false, 2000), cell("Reference", false, false, 4260)] }),
  new TableRow({ children: [cell("Wound-only (true mask)", false, false, 3100), cell("0.670", false, false, 2000), cell("vs full −0.055 (0.62)", false, false, 4260)] }),
  new TableRow({ children: [cell("Background-only (true mask)", false, false, 3100), cell("0.821", false, false, 2000), cell("vs full +0.097 (0.09)", false, false, 4260)] }),
  new TableRow({ children: [cell("Sham wound (relocated mask)", false, false, 3100), cell("0.817", false, false, 2000), cell("vs true background −0.005 (0.94); vs true wound +0.147 (0.08)", false, false, 4260)] }),
  new TableRow({ children: [cell("Sham background", false, false, 3100), cell("0.654", false, false, 2000), cell("vs full −0.071 (0.16)", false, false, 4260)] }),
]});

const doc = new Document({
  styles: { default: { document: { run: { font: "Calibri", size: 21 } } } },
  sections: [{
    properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } } },
    children: [
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 140 }, children: [new TextRun({ text: "Paper 1 — Working draft for revision (Results, Methods, Discussion)", bold: true, size: 27 })] }),
      P([I("Working draft prepared with AI assistance as raw material for the author's own revision; not for submission in this form. All numbers are verified against the released row-level out-of-fold predictions and the locked master fold map. Two items remain provisional pending PI decisions and are highlighted where they appear: (i) the clinical-model specification (physiological range-check of temperature covariates, 30–43°C), and (ii) the day assignment of 318 photographs labelled 'post' without a day number, which affects the primary estimate (0.761 as analysed; 0.730 if those photographs are excluded).")], { alignment: AlignmentType.LEFT }),

      H1("RESULTS"),
      H2("Cohort and image characteristics"),
      P([T("The analytic cohort comprised 1,948 quality-gated smartphone photographs from 210 adults, of whom 20 (9.5%) developed a surgical site infection (SSI) within 30 days. Patients submitted a median of 8 photographs overall (6 among SSI patients and 8 among those without SSI; IQR 5–11 overall; range 1–43). Imaging was scheduled at protocol postoperative days (POD) 4, 7, 10, 14 and 30, with day-of-surgery baseline photographs; additional photographs were submitted off-schedule throughout the follow-up window. "), FLAG("[PI to confirm protocol wording: the written protocol may specify day 2, but only 17 photographs were captured on day 2 versus 104 on day 4.]"), T(" By POD 7, 94% of patients had submitted at least one photograph (Table 1). Because there were 20 events, all interval estimates were wide, and null findings should not be interpreted as evidence of equivalence. Analyses use nested frames of the 210-patient cohort: 204 patients for the leak sensitivity (excluding 2 SSI patients without adjudicable diagnosis dates and 4 patients without dated photographs), 193 for the POD-7 risk set (further excluding patients diagnosed by day 7), and 206 patients (19 events) for the masking analyses (annotation availability).")]),
      t1,
      P([I("Table 1 | Cohort and imaging characteristics by SSI status. Baseline characteristics (age, sex, comorbidity) were available only for an outcome-correlated chart-review subset and are reported in the Supplement with that caveat; intraoperative fields are from the outcome-neutral intraoperative export (incision length recorded in 126/210).")], { alignment: AlignmentType.LEFT, spacing: { before: 80, after: 200 } }),

      H2("Primary pre-diagnosis discrimination"),
      P([T("The primary analysis was performed at the prespecified POD-7 landmark, among 193 patients not yet diagnosed with SSI, of whom 15 subsequently developed an infection. Scoring each patient as the mean model probability across all photographs obtained through POD 7, the image-only model achieved an AUROC of 0.761 (95% CI 0.645–0.860) and an AUPRC of 0.172 against a risk-set prevalence of 7.8% (Fig. 1). Results were similar using the latest photograph through POD 7 (AUROC 0.746) or the photograph closest to POD 7 (0.744). "), FLAG("[Provisional pending PI ruling on the 'post' phase label: excluding the 318 photographs with an unnumbered 'post' label gives 0.730 (187 patients, 14 events).]")]),

      H2("Estimand robustness"),
      P("Restricting positive patients to photographs obtained strictly before diagnosis had little effect on the pooled patient-level estimate (paired same-patient Δ +0.007, 95% CI −0.011 to +0.025; P=0.44; 204 patients, 18 with adjudicated diagnosis dates). The all-images analysis gave a patient-level AUROC of 0.779 and is reported as a sensitivity analysis. The observed discrimination was therefore not attributable to photographs taken after diagnosis."),

      H2("Architecture and seed variability"),
      P("Three random seeds were evaluated per architecture on the identical locked folds (Table 2; Fig. 2a). Mean patient-level AUROC was 0.755±0.037 for EfficientNet-B0, 0.731±0.052 for ResNet18 and 0.725±0.049 for ViT-B/16. No architecture significantly outperformed another (paired P=0.10–0.93), rankings changed across seeds, and within-architecture seed variation was of similar magnitude to between-architecture variation: the largest observed contrast was between two ResNet18 seeds (−0.102; P=0.09), marginally exceeding the largest between-architecture contrast (ViT-B/16 seed 7 versus reference, −0.099; P=0.10). Mean AUROC was 0.718±0.016 with one-third of training patients, 0.746±0.057 with two-thirds and 0.755±0.037 with the full cohort (Fig. 2b), with no clear increase across training-set sizes."),
      t2,
      P([I("Table 2 | Fold-paired architectures on the locked master map. All models used identical folds and training procedures, evaluated across three seeds.")], { alignment: AlignmentType.LEFT, spacing: { before: 80, after: 200 } }),

      H2("Confound and context probes"),
      P("Postoperative day alone discriminated near chance at the image level. At the patient level, the image model exceeded each individual context probe consistently across seeds (vs POD +0.067±0.052; vs acquisition characteristics +0.058±0.052; vs prior imaging behaviour +0.061±0.052). A combined context-only model using acquisition characteristics, imaging behaviour and POD together — with no access to wound pixels — approximately matched the image model (Δ −0.009±0.052)."),

      H2("Spatial localisation: masking with sham controls"),
      P("The masking analysis included 1,886 photographs from 206 patients (19 with SSI); one SSI-positive patient had no available annotation source and is itemised in the released audit. Patient-level AUROC was 0.725 for the full image, 0.670 for wound-only input and 0.821 for background-only input (Table 3; Fig. 3); wound-only did not exceed the full image. A randomly relocated mask of equal area to the true wound mask produced an AUROC of 0.817, indistinguishable from the true background condition (Δ −0.005; P=0.94). The true wound crop performed numerically worse than the equal-area random patch (Δ +0.147 favouring the sham; P=0.08), and the apparent background-versus-full difference did not persist against its sham control (P=0.16). Similar results were therefore produced by mask geometry alone, without correspondence to wound location."),
      t3,
      P([I("Table 3 | Masked retraining with sham controls (annotation-available frame; frozen master folds; paired patient-bootstrap contrasts).")], { alignment: AlignmentType.LEFT, spacing: { before: 80, after: 200 } }),

      H2("Healing-stage positive control"),
      P("Using the same photographs and identical pipeline, normal postoperative healing stage was identified with an AUROC of approximately 0.975, compared with approximately 0.755 for SSI."),

      H2("Calibration and operating points"),
      P("For the POD-7 primary, Platt-scaled probabilities gave a Brier score of 0.075 (95% CI 0.047–0.106) and a calibration slope of 0.63 (95% CI 0.30–1.05). At 80% specificity, sensitivity was 0.67 with 24% of patients flagged. A higher-sensitivity threshold detected 14 of 15 infections (93%) while flagging 51% of patients (specificity 0.53). Predictive values are not emphasised given 20 events."),

      H2("Image versus clinical versus combined models"),
      P([FLAG("[Provisional pending PI approval of the 30–43°C range-check on temperature covariates; 11 physiologically implausible entries removed.] "), T("On the locked cohort under the range-checked specification, AUROC was 0.747 for the clinical model (intraoperative covariates only; coverage outcome-neutral), 0.779 for the image model and 0.794 for the combined model; the combined-versus-clinical difference was not significant (Δ +0.048; P=0.13). Before range-checking, the same contrast reached Δ +0.116 (P=0.013 at the primary cross-validation partition), but this result was unstable across partitions (P=0.17 and 0.20 at two alternative partitions) and disappeared when the image component was restricted to pre-diagnosis photographs (Δ +0.025; P=0.67), indicating that it was carried by implausible covariate values and post-diagnosis image information rather than prospective signal. Within the leak-free POD-7 risk set, the combined model showed no AUROC gain over the image model (Δ −0.020; P=0.80) and a non-significant AUPRC difference (0.277 vs 0.172; Δ +0.106; P=0.18); decision curves overlapped. A clinical specification based on chart-reviewed variables was excluded because the availability of chart-review data itself predicted SSI (coverage-indicator AUROC approximately 0.75).")]),

      H2("Model versus clinicians"),
      P("Fifteen clinicians rated a shared image set. Inter-rater agreement was slight (Fleiss κ=0.105), with no difference between surgeons and non-surgeons. On the shared set restricted to pre-diagnosis images, AUROC was 0.89 for the model and 0.63 for the clinician consensus; this subset contained three SSI-positive patients and the difference was not significant (P=0.33). The comparison is reported as exploratory in the Supplement."),

      new Paragraph({ children: [new PageBreak()] }),
      H1("DISCUSSION"),
      P("In this prospective surveillance cohort, smartphone photographs obtained before diagnosis carried a moderate but real signal for subsequent surgical site infection: at the POD-7 landmark, image-only discrimination was 0.761 (95% CI 0.645–0.860) with an AUPRC of 0.172. This estimate was robust to the exclusion of post-diagnosis photographs. No stable architectural gain emerged across ResNet18, EfficientNet-B0 and ViT-B/16 over multiple seeds; a context-only model built from acquisition characteristics, imaging behaviour and postoperative day approximately matched the image model; and masking analyses produced no evidence of semantic wound localisation, with sham masks reproducing the true-mask results. The context-only finding deserves emphasis in its own right: at the patient level, when and how photographs are taken encodes nearly as much outcome-relevant information as what the photographs show — a property of remote-surveillance data itself, not only of any particular model."),
      P("Moderate discrimination should not be mistaken for clinically sufficient precision. An AUROC of 0.76 describes ranking, not usable certainty: the AUPRC of 0.172 sits against a prevalence floor of 0.078, roughly twice chance-level precision and far below what screening requires. The operating points make the same point concretely — detecting 14 of 15 infections required flagging 51% of patients (specificity 0.53). Ranking and precision diverge at low prevalence, and both numbers belong on the page together."),
      P("The strongest evidence that the input, rather than the model, constrains performance comes from the healing-stage positive control: the identical photographs, processed by the identical pipeline, encoded normal postoperative stage almost perfectly (≈0.975) while encoding infection only moderately (≈0.755). This within-substrate contrast does not depend on the event count. The architecture and training-size analyses point the same way — no architecture outperformed another, rankings changed with seed, and performance did not rise with more training data — but these are underpowered nulls: with 15–20 events and paired-interval half-widths of 0.10–0.16, a true architecture effect below that resolution cannot be excluded. We therefore read the architecture results as supporting, not proving, an input limitation."),
      P("Several mechanisms plausibly account for the context sensitivity of the image signal: dressings and framing, periwound skin, body site, postoperative timing, and the behaviour of image submission itself. The sham-mask experiment adds a methodological conclusion with implications beyond this study: because a randomly placed mask of equal area performed like the true wound mask, masking and ablation cannot establish that a model uses wound-specific features. The CAM/attention and incision-ablation practices this field relies on to claim biological validity do not, on their own, demonstrate what they are taken to demonstrate; a geometry control is required. One further consequence of an RGB bottleneck is not neutral: erythema is the cardinal visual cue of infection and is harder to resolve on darker skin, so an information limit in single RGB photographs is likely to fall hardest on the patients remote surveillance is intended to reach."),
      P("The comparison with clinical data should be read on the prospective frame. On the full cohort, an apparently significant combined-versus-clinical gain proved fragile: it depended on physiologically implausible covariate entries and on post-diagnosis image information, and it vanished when the image component was restricted to pre-diagnosis photographs. On the leak-free POD-7 frame there was no AUROC gain and only a non-significant AUPRC trend. The full cohort admits post-diagnosis information that inflates the image's apparent contribution; the prospective frame does not. We therefore qualify the conclusion of limited unique image information to the prospective surveillance setting, which is the setting the estimand was designed to measure."),
      P("The contribution of this study relative to prior work is the audit, not the observation that images can be insufficient. Image-based diagnosis has succeeded where the diagnostic information is genuinely in the pixels — diabetic retinopathy, skin-cancer morphology, histopathology — and the same transfer-learning machinery that succeeds there plateaus here, which is itself evidence about the substrate. Prior smartphone-SSI studies, including the largest to date, report moderate image performance or multimodal benefit and validate attention with CAM or heatmap inspection; to our knowledge none combines a prospective pre-diagnosis estimand with sham-controlled localisation, architecture-by-seed testing, context-only probes and a within-substrate positive control. [PI: add the second named comparator and citations here.]"),
      P("Strengths of this study include prospective acquisition, locked patient-grouped folds with strictly out-of-fold predictions, a timing-aligned leak-free primary estimand, independence of index images from the reference standard, and multiple convergent audits of the same signal. The principal limitation is precision: the primary estimate rests on 15 events, and its interval — 0.645 to 0.860 — is compatible with marginal to clinically meaningful discrimination; the point estimate is a best guess, not a precise measurement. Additional limitations include a single centre and device workflow, missing scheduled photographs and photographs without recorded day labels, exclusions in the masking subset determined by annotation availability, model and seed instability, the exploratory clinician comparison, and the absence of external validation. Skin-tone distribution was not analysed; given the erythema mechanism, performance across skin tones is a priority open question."),
      P("These findings support multimodal prospective surveillance systems rather than image-only screening: standardised acquisition, calibrated decision support built around an explicit rule-out flag rate, and external validation in independent cohorts — including skin-tone-diverse cohorts, so that the equity question raised here is answered rather than assumed. They also support a methods standard for the field: validation of image-AI in wound surveillance should require sham or permutation spatial controls and seed-distribution reporting, not attention-map inspection. Taken together, the results are consistent with an information limit in single RGB photographs: informative adjuncts, incomplete as standalone diagnostic inputs, with the constraint residing in what is captured rather than in how it is modelled."),

      new Paragraph({ children: [new PageBreak()] }),
      H1("METHODS"),
      H2("Study design and setting"),
      P("This was a prospective SSI-surveillance feasibility study at a single academic centre, with serial smartphone photography of the surgical incision scheduled across the 30-day postoperative window. Reporting follows TRIPOD for prediction models and STROBE where applicable; the analysis plan was prespecified before exposure–outcome modelling. The aim was to quantify how much infection-specific information a single RGB photograph contains, rather than to develop a classifier for deployment."),
      H2("Participants and cohort"),
      P("Adults undergoing surgery with a qualifying incision were enrolled. The analytic set comprised 1,948 quality-gated photographs from 210 patients; 20 (9.5%) developed SSI. Before locking membership, enrolment and outcomes were adjudicated: one duplicate enrolment was resolved (the SSI-positive record retained), consent withdrawals were identified and excluded, and SSI labels and diagnosis dates were adjudicated. None of the adjudicated records contributed analytic images; the cohort remained 210 patients with 20 events."),
      H2("Image acquisition and quality gating"),
      P([T("Photographs were captured by patients or staff on their own smartphones; devices and lighting were uncontrolled by design. A protocolised quality and dressing gate was applied prospectively and without knowledge of outcome: photographs passed when the incision was visible and free of dressing; dressing-covered, non-wound and unusable frames failed. Gate passage was 56% of photographs from SSI-positive patients and 60% from SSI-negative patients. The gate is an automatable pipeline step rather than retrospective selection. All analyses used one locked master image–fold map (1,948 unique photographs; patient-grouped folds fixed under seed 42), released for audit. "), FLAG("[Note for PI: 318 photographs carry the phase label 'post' with no day number and are assigned to day 0 by convention; their day assignment is under review and a sensitivity excluding them is reported with the primary analysis.]")]),
      H2("Reference standard"),
      P("The outcome was 30-day SSI by CDC/NHSN criteria from structured chart review. Study photographs were not available to the adjudicating team and did not inform any diagnosis; index images were therefore independent of the reference standard."),
      H2("Primary estimand and outcome"),
      P("The primary estimand was detection before diagnosis at a POD-7 landmark: among patients not yet diagnosed by POD 7 (two SSI-positive patients with unadjudicable diagnosis dates excluded), subsequent SSI was predicted from the mean model probability of all photographs obtained through POD 7 (193 patients, 15 events). Prespecified aggregation sensitivities used the latest photograph through POD 7 and the photograph closest to POD 7."),
      H2("Model development and validation"),
      P("Two convolutional architectures (ResNet18, EfficientNet-B0) and a vision transformer (ViT-B/16) were fine-tuned end-to-end from ImageNet weights (12 epochs; AdamW; learning rate 1×10⁻⁴, 3×10⁻⁵ for ViT; flip augmentation; class-weighted cross-entropy; 224×224 inputs). Validation used patient-grouped five-fold cross-validation with strictly out-of-fold predictions; patient-level scores were the mean of each patient's image probabilities. Each architecture was trained at three random seeds on identical folds. All metrics and resampling were clustered at the patient level."),
      H2("Statistical analysis"),
      P("AUROC and AUPRC were co-primary, with Brier score and calibration slope/intercept for probability quality. Confidence intervals used 2,000 patient-level clustered bootstrap resamples; all model comparisons were paired within the same bootstrap replicate. The primary estimand and its leak sensitivity formed a prespecified confirmatory set; all other analyses were exploratory and reported descriptively. Observed paired-interval half-widths (approximately 0.10–0.16 AUROC) are reported as the design's resolution, and model differences are reported as distributions across seeds rather than single point estimates."),
      H2("Information audit and confounding analyses"),
      P("Four prespecified probes were performed. (a) Architecture × seed: three architectures at three seeds on identical folds, with between- and within-architecture paired deltas interpreted against seed variance. (b) Context probes: models built only from postoperative day, image-acquisition characteristics, or prior imaging behaviour (past-only, leak-audited), each compared with the image model, plus a combined context-only model. (c) Spatial masking with sham controls: retraining on full, wound-only and background-only inputs using expert incision annotations (incision-line strips and wound-bed polygons with a tolerance band), and on randomly relocated equal-area sham masks, with paired deltas versus full and real-versus-sham contrasts. (d) Healing-stage positive control: the same photographs and pipeline predicting normal postoperative stage."),
      H2("Calibration, operating points and decision curves"),
      P("Raw scores were used for discrimination; cross-fold Platt scaling for probability and operating-point claims. Recalibration was unstable at this event count and isotonic calibration was degenerate; both are stated. Prespecified operating points (fixed specificity; high-sensitivity rule-out) are reported with sensitivity, flag rate and clustered intervals. Decision-curve net benefit was computed against treat-all and treat-none across a plausible threshold range, with intervals."),
      H2("Comparative analyses"),
      P([T("Image, clinical and combined models were compared on the locked cohort with paired ΔAUROC/ΔAUPRC. The clinical model used intraoperative covariates only, because chart-review availability was outcome-correlated and specifications encoding ascertainment were excluded from inference. "), FLAG("[Provisional: temperature covariates outside 30–43°C (11 entries) were set to missing pending PI approval of this range check.] "), T("The clinician panel rated identical images (pre-diagnosis-restricted contrast; Fleiss κ; surgeon versus non-surgeon strata); these analyses were prespecified as exploratory given few SSI-positive patients in the shared-rated subset.")]),
      H2("Reproducibility"),
      P("The pipeline is deterministic under the fixed seed set. The locked master fold map, row-level out-of-fold predictions for every architecture × seed × masking condition, the masking cohort audit (all exclusions with reasons; annotation availability, not outcome), and analysis code organised by stage are released."),
    ],
  }],
});

Packer.toBuffer(doc).then((buf) => {
  fs.writeFileSync(process.argv[2] || "PAPER1_working_draft_v4.docx", buf);
  console.log("DOCX_WRITTEN");
});
